##@package src.mainwindow
#The most Top Level entry point for DDS AD9910
#@author Newell Jensen

from src.callbacks import *

class mainwindow(gtk.Window):
    """
    Top-level Window for the DDS-AD9910 board.
    """
    def __init__(self):
        gtk.Window.__init__(self)
        self.connect('destroy', cb_destroy, self)
        self.set_title('DDS AD9910')
        ## self.set_icon_from_file('images/icons/geda-xgsch2pcb-48.png')
        self.set_size_request(750,500)
        self.sysclk = 25.0 # Default sysclk in MHz
 
        # Create a Menu UIManager and a Popup UIManager
        self.menu_uimanager = gtk.UIManager()

        # init methods
        self.__init_menus__()
        self.__init_window_sections__()
        self.__init_about_dialog__()
        self.show_all()


    #####################################################
    # Initializer Methods -- methods to create the window
    #####################################################

    def __init_menus__(self):
        """ Method to create the menu bar. """

        actiongroup0 = gtk.ActionGroup('DDS_AD9910')
        actiongroup0_list = [('File', None, '_File'),
        ('New File', None, 'Ne_w File', None, None, cb_new_file),
        ('Open File', None, 'Open F_ile', None, None, cb_open_file),
        ('Close File', None, 'Close Fil_e', None, None, cb_close_file),
        ('Exit', gtk.STOCK_QUIT, 'E_xit', '<Control>q', None, cb_destroy),
        ('I/O', None, '_I/O'),
        ('View', None, '_View'),
        ('Control Window', None, '_Control Window', None, None, cb_open_control_window),
        ('Profile Window', None, '_Profile Window', None, None, cb_open_profile_window),
        ('QSK Digital Ramp Control Window', None, '_QSK Digital Ramp Control Window', None, None, cb_open_qsk_window),
        ('RAM Input-Output Window', None, '_RAM Input-Output Window', None, None, cb_open_ram_window),
        ('Register Map Values Window', None, '_Register Map Values Window', None, None, cb_open_register_window),
        ('Debug Window', None, '_Debug Window', None, None, cb_open_debug_window),
        ('Help', None, '_Help'),
        ('About', gtk.STOCK_ABOUT, '_About', None, None, cb_show_about_dialog),]
        actiongroup0.add_actions(actiongroup0_list, self)
        self.menu_uimanager.insert_action_group(actiongroup0, 0)
        merge_id = self.menu_uimanager.add_ui_from_file('src/xml/menu.xml')
        menubar = self.menu_uimanager.get_widget('/MenuBar')
        toolbar = gtk.Toolbar()
        toolbar.append_item('I/O Update', 'Assert I/O Update Pin', None, None, cb_ioupdate, None)
        toolbar.append_item('Load', 'Load New Date into DDS', None, None, cb_load, None)
        self.vbox = gtk.VBox()
        self.add(self.vbox)
        self.vbox.pack_start(menubar, False, False, 0)
        self.vbox.pack_start(toolbar, False, False, 0)
        
        # Set up tooltips
        widget = self.menu_uimanager.get_widget('/MenuBar/File/New File')
        widget.set_tooltip_text('Create New File')
        widget = self.menu_uimanager.get_widget('/MenuBar/File/Open File')
        widget.set_tooltip_text('Open File')
        widget = self.menu_uimanager.get_widget('/MenuBar/File/Close File')
        widget.set_tooltip_text('Close File')
        widget = self.menu_uimanager.get_widget('/MenuBar/File/Exit')
        widget.set_tooltip_text('Exit Program')
        widget = self.menu_uimanager.get_widget('/MenuBar/View/Control Window')
        widget.set_tooltip_text('View Control Window')
        widget = self.menu_uimanager.get_widget('/MenuBar/View/Profile Window')
        widget.set_tooltip_text('View Profile Window')
        widget = self.menu_uimanager.get_widget('/MenuBar/View/QSK Digital Ramp Control Window')
        widget.set_tooltip_text('View QSK Digital Ramp Control Window')
        widget = self.menu_uimanager.get_widget('/MenuBar/View/RAM Input-Output Window')
        widget.set_tooltip_text('View Ram I/O Window')        
        widget = self.menu_uimanager.get_widget('/MenuBar/View/Register Map Values Window')
        widget.set_tooltip_text('View Register Map Values Window')        
        widget = self.menu_uimanager.get_widget('/MenuBar/View/Debug Window')
        widget.set_tooltip_text('View Debug Window')        
        widget = self.menu_uimanager.get_widget('/MenuBar/Help/About')
        widget.set_tooltip_text('Time for some praise')        


    def __init_window_sections__(self):
        """ Method to create the main gui sections of the top-level window. """

        ### Top-level Notebook
        notebook = gtk.Notebook()
        self.vbox.pack_start(notebook)
        notebook.set_tab_pos(gtk.POS_TOP)
        control_box = gtk.HBox()
        profile_box = gtk.HBox()
        qsk_box = gtk.HBox()
        register_box = gtk.HBox()
        debug_box = gtk.HBox()
        notebook.add(control_box)
        notebook.add(profile_box)
        notebook.add(qsk_box)
        notebook.add(register_box)
        notebook.add(debug_box)
        control_label = gtk.Label('Control')
        profile_label = gtk.Label('Profile')
        qsk_label = gtk.Label('QSK Digital Ramp')
        register_label = gtk.Label('Register Values')
        debug_label = gtk.Label('Debug')
        notebook.set_tab_label(notebook.get_nth_page(0), control_label)
        notebook.set_tab_label(notebook.get_nth_page(1), profile_label)
        notebook.set_tab_label(notebook.get_nth_page(2), qsk_label)
        notebook.set_tab_label(notebook.get_nth_page(3), register_label)        
        notebook.set_tab_label(notebook.get_nth_page(4), debug_label)

        ## Control Window
        # Frames
        clk_frame = gtk.Frame('Clock')
        enable_multi_frame = gtk.Frame()
        io_frame = gtk.Frame('I/O Update')
        internal_io_frame = gtk.Frame()
        aux_frame = gtk.Frame('AUX Dac Control')
        pwrdn_frame = gtk.Frame('Power Down')
        # Frames in Control Box
        vbox = gtk.VBox()        
        vbox.pack_start(clk_frame)
        vbox.pack_start(io_frame)
        control_box.pack_start(vbox)
        vbox = gtk.VBox()
        vbox.pack_start(pwrdn_frame)
        vbox.pack_start(aux_frame)
        control_box.pack_start(vbox)
        # Add VBoxs to Frames
        clk_box = gtk.VBox()
        enable_box = gtk.VBox()
        io_box = gtk.VBox()
        internal_io_box = gtk.VBox()
        aux_box = gtk.VBox()
        pwrdn_box = gtk.VBox()
        clk_frame.add(clk_box)
        enable_multi_frame.add(enable_box)                
        io_frame.add(io_box)
        internal_io_frame.add(internal_io_box)
        aux_frame.add(aux_box)
        pwrdn_frame.add(pwrdn_box)
        # Clock Frame
        enable_multiplier_button = gtk.CheckButton('Enable Multiplier')
        clk_box.pack_start(enable_multiplier_button, False, False, 5)
        clk_box.pack_start(enable_multi_frame)
        hbox = gtk.HBox()
        multiplier_label = gtk.Label('Multiplier: ')
        hbox.pack_start(multiplier_label, False, False)
        multi_adj = gtk.Adjustment(12.0, 12.0, 40.0, 1.0, 5.0, 0.0)
        multiplier_spin = gtk.SpinButton(multi_adj, 0, 0)
        hbox.pack_start(multiplier_spin, False, False, 5)
        enable_box.pack_start(hbox, False, False, 5)
        hbox = gtk.HBox()
        cp_label = gtk.Label('CP Current (micro amps): ')
        cp_combo = gtk.combo_box_new_text()
        cp_combo.append_text('387')
        cp_combo.append_text('363')
        cp_combo.append_text('337')
        cp_combo.append_text('312')
        cp_combo.append_text('287')
        cp_combo.append_text('262')
        cp_combo.append_text('237')
        cp_combo.append_text('212')
        cp_combo.set_active(0)
        hbox.pack_start(cp_label, False, False)
        hbox.pack_start(cp_combo, False, False, 5)
        enable_box.pack_start(hbox, False, False, 5)
        hbox = gtk.HBox()
        vco_label = gtk.Label('VCO Range: ')
        vco_combo = gtk.combo_box_new_text()
        vco_combo.append_text('420 MHz - 485 MHz')
        vco_combo.append_text('482 MHz - 562 MHz')
        vco_combo.append_text('562 MHz - 656 MHz')
        vco_combo.append_text('656 MHz - 832 MHz')
        vco_combo.append_text('832 MHz - 932 MHz')
        vco_combo.append_text('932 MHz - 1030 MHz')
        vco_combo.set_active(5)
        hbox.pack_start(vco_label, False, False)
        hbox.pack_start(vco_combo, False, False, 5)
        enable_box.pack_start(hbox, False, False)
        hbox = gtk.HBox()
        pll_status = gtk.Statusbar()
        context_id = pll_status.get_context_id('PLL Locked')
        pll_label = gtk.Label('PLL Locked')
        pll_button = gtk.Button('Refresh')
        pll_button.connect('clicked', cb_pll_button_pushed, context_id, pll_status)
        hbox.pack_start(pll_status)
        hbox.pack_start(pll_label, False, False, 5)
        hbox.pack_start(pll_button, False, False, 5)
        enable_box.pack_start(hbox, False, False)
        hbox = gtk.HBox()
        sysclk_label = gtk.Label('System CLock: ')
        sysclk_display = gtk.Entry()
        sysclk_display.set_editable(False)
        sysclk_display.set_text(str(self.sysclk))
        label = gtk.Label('MHz')
        hbox.pack_start(sysclk_label, False, False)
        hbox.pack_start(sysclk_display, False, False, 5)
        hbox.pack_start(label, False, False, 5)
        clk_box.pack_start(hbox, False, False, 5)
        # I/O Update Frame
        io_button = gtk.CheckButton('Use Internal I/O Update')
        io_box.pack_start(io_button, False, False, 5)
        io_box.pack_start(internal_io_frame)
        hbox = gtk.HBox()
        io_label = gtk.Label('I/O Update Clock Divider: ')
        io_combo = gtk.combo_box_new_text()
        io_combo.append_text('1')
        io_combo.append_text('2')
        io_combo.append_text('3')
        io_combo.append_text('4')
        io_combo.set_active(0)
        hbox.pack_start(io_label, False, False)
        hbox.pack_start(io_combo, False, False, 5)
        internal_io_box.pack_start(hbox, False, False, 5)
        hbox = gtk.HBox()
        io_label = gtk.Label('I/O Update Rate Period (secs): ')
        io_display = gtk.Entry()
        io_display.set_editable(False)
        hbox.pack_start(io_label, False, False)        
        hbox.pack_start(io_display, False, False, 5)
        internal_io_box.pack_start(hbox, False, False, 5)
        # Aux Frame
        hbox = gtk.HBox()
        aux_label = gtk.Label('DAC Gain Control: ')
        aux_adj = gtk.Adjustment(127.0, 0.0, 255.0, 1.0, 5.0, 0.0)
        aux_spin = gtk.SpinButton(aux_adj, 0, 0)
        aux_spin.set_wrap(True)
        hbox.pack_start(aux_label, False, False)
        hbox.pack_start(aux_spin, False, False, 5)
        aux_box.pack_start(hbox, False, False, 5)
        hbox = gtk.HBox()
        iout_label = gtk.Label('Dac Iout: ')
        iout_display = gtk.Entry()
        iout_display.set_editable(False)
        iout_label2 = gtk.Label('mA')
        hbox.pack_start(iout_label, False, False)
        hbox.pack_start(iout_display, False, False, 5)
        hbox.pack_start(iout_label2, False, False, 5)
        aux_box.pack_start(hbox, False, False)
        # Power Down Frame
        digital_button = gtk.CheckButton('Digital')
        dac_button = gtk.CheckButton('DAC')
        clkinput_button = gtk.CheckButton('Clock Input')
        auxdac_button = gtk.CheckButton('Aux DAC')
        separator = gtk.HSeparator()
        autopd_button = gtk.CheckButton('Enable Auto PD')
        extpwr_label = gtk.Label('External PD Mode: ')
        pdmode_combo = gtk.combo_box_new_text()
        pdmode_combo.append_text('Fast Recovery')
        pdmode_combo.append_text('Full Power Down')
        pdmode_combo.set_active(0)
        pwrdn_label = gtk.Label('External Power Down Pin:')
        button1 = gtk.RadioButton(None, 'Logic 1')
        button1.connect('toggled', cb_ext_pwr_pin_toggled, 'Logic 1')
        button2 = gtk.RadioButton(button1, 'Logic 0')
        button2.connect('toggled', cb_ext_pwr_pin_toggled, 'Logic 0')
        pwrdn_box.pack_start(digital_button)
        pwrdn_box.pack_start(dac_button)
        pwrdn_box.pack_start(clkinput_button)
        pwrdn_box.pack_start(auxdac_button)
        pwrdn_box.pack_start(separator)
        pwrdn_box.pack_start(autopd_button, False, False, 5)
        pwrdn_box.pack_start(extpwr_label)
        pwrdn_box.pack_start(pdmode_combo, False, False, 5)
        pwrdn_box.pack_start(pwrdn_label, False, False, 5)
        pwrdn_box.pack_start(button1)
        pwrdn_box.pack_start(button2)

        ## Profile Window
        profile_vbox = gtk.VBox()
        profile_box.pack_start(profile_vbox)
        profile_notebook = gtk.Notebook()
        profile_vbox.pack_end(profile_notebook)
        profile_notebook.set_tab_pos(gtk.POS_BOTTOM)
        # Tabbed Windows
        profile0_vbox = gtk.VBox()
        profile0_vbox.set_border_width(10)
        profile1_vbox = gtk.VBox()
        profile1_vbox.set_border_width(10)
        profile2_vbox = gtk.VBox()
        profile2_vbox.set_border_width(10)
        profile3_vbox = gtk.VBox()
        profile3_vbox.set_border_width(10)
        profile4_vbox = gtk.VBox()
        profile4_vbox.set_border_width(10)
        profile5_vbox = gtk.VBox()
        profile5_vbox.set_border_width(10)
        profile6_vbox = gtk.VBox()
        profile6_vbox.set_border_width(10)
        profile7_vbox = gtk.VBox()
        profile7_vbox.set_border_width(10)
        # Add Tabbed Windows to Notebook
        profile_notebook.add(profile0_vbox)
        profile_notebook.add(profile1_vbox)
        profile_notebook.add(profile2_vbox)
        profile_notebook.add(profile3_vbox)
        profile_notebook.add(profile4_vbox)
        profile_notebook.add(profile5_vbox)
        profile_notebook.add(profile6_vbox)
        profile_notebook.add(profile7_vbox)
        # Labels
        profile0_label = gtk.Label('Profile 0')
        profile1_label = gtk.Label('Profile 1')
        profile2_label = gtk.Label('Profile 2')
        profile3_label = gtk.Label('Profile 3')
        profile4_label = gtk.Label('Profile 4')
        profile5_label = gtk.Label('Profile 5')
        profile6_label = gtk.Label('Profile 6')
        profile7_label = gtk.Label('Profile 7')
        profile_notebook.set_tab_label(profile_notebook.get_nth_page(0), profile0_label)
        profile_notebook.set_tab_label(profile_notebook.get_nth_page(1), profile1_label)
        profile_notebook.set_tab_label(profile_notebook.get_nth_page(2), profile2_label)
        profile_notebook.set_tab_label(profile_notebook.get_nth_page(3), profile3_label)
        profile_notebook.set_tab_label(profile_notebook.get_nth_page(4), profile4_label)        
        profile_notebook.set_tab_label(profile_notebook.get_nth_page(5), profile5_label)
        profile_notebook.set_tab_label(profile_notebook.get_nth_page(6), profile6_label)
        profile_notebook.set_tab_label(profile_notebook.get_nth_page(7), profile7_label)
        enable_profile_asf_button = gtk.CheckButton('Enable Profile ASF')
        enable_sine_out_button = gtk.CheckButton('Enable Sine Out')
        enable_RAM_button = gtk.CheckButton('Enable RAM')
        RAM_data_type_label = gtk.Label('RAM Data Type: ')
        internal_profile_ctrl_label = gtk.Label('Internal Profile Control: ')
        internal_profile_ctrl_combo = gtk.combo_box_new_text()
        internal_profile_ctrl_combo.append_text('Disabled')
        internal_profile_ctrl_combo.append_text('Profile0-Profile1, then halt')
        internal_profile_ctrl_combo.append_text('Profile0-Profile2, then halt')
        internal_profile_ctrl_combo.append_text('Profile0-Profile3, then halt')
        internal_profile_ctrl_combo.append_text('Profile0-Profile4, then halt')
        internal_profile_ctrl_combo.append_text('Profile0-Profile5, then halt')
        internal_profile_ctrl_combo.append_text('Profile0-Profile6, then halt')
        internal_profile_ctrl_combo.append_text('Profile0-Profile7, then halt')
        internal_profile_ctrl_combo.append_text('Profile0-Profile1, continuously')
        internal_profile_ctrl_combo.append_text('Profile0-Profile2, continuously')
        internal_profile_ctrl_combo.append_text('Profile0-Profile3, continuously')
        internal_profile_ctrl_combo.append_text('Profile0-Profile4, continuously')
        internal_profile_ctrl_combo.append_text('Profile0-Profile5, continuously')
        internal_profile_ctrl_combo.append_text('Profile0-Profile6, continuously')
        internal_profile_ctrl_combo.append_text('Profile0-Profile7, continuously')
        internal_profile_ctrl_combo.set_active(0)
        load_RAM_button = gtk.Button('Load RAM')
        load_RAM_FILE_button = gtk.Button('RAM I/O Load/File')
        RAM_data_type_combo = gtk.combo_box_new_text()
        RAM_data_type_combo.append_text('Frequency')
        RAM_data_type_combo.append_text('Phase')
        RAM_data_type_combo.append_text('Amplitude')
        RAM_data_type_combo.append_text('Polar (phase and amplitude)')
        RAM_data_type_combo.set_active(0)
        RAM_sw_over_label = gtk.Label('RAM Sweep Over: ')
        RAM_sw_over_image = gtk.Image()
        RAM_sw_over_image.set_from_stock(gtk.STOCK_NO, gtk.ICON_SIZE_BUTTON)
        profile_hbox = gtk.HBox()
        profile_hbox.pack_start(enable_profile_asf_button)
        profile_hbox.pack_start(enable_sine_out_button)
        profile_hbox.pack_start(enable_RAM_button)
        profile_vbox.pack_start(profile_hbox, False, False, 5)
        profile_separator = gtk.HSeparator()
        profile_vbox.pack_start(profile_separator, False, False, 5)
        profile_hbox = gtk.HBox()
        profile_hbox.pack_start(internal_profile_ctrl_label, False, False, 10)
        profile_hbox.pack_start(internal_profile_ctrl_combo, False, False, 10)
        profile_hbox.pack_start(load_RAM_button, False, False, 10)
        profile_hbox.pack_start(load_RAM_FILE_button, False, False, 10)
        profile_vbox.pack_start(profile_hbox, False, False, 5)
        profile_hbox = gtk.HBox()
        profile_hbox.pack_start(RAM_data_type_label, False, False, 10)
        profile_hbox.pack_start(RAM_data_type_combo)
        profile_hbox.pack_start(RAM_sw_over_label)
        profile_hbox.pack_start(RAM_sw_over_image)
        profile_vbox.pack_start(profile_hbox, False, False, 5)
        # Populate profile tabs
        # Output Frequency Section
        profile0_freq_label = gtk.Label('Freq (MHz): ')
        profile1_freq_label = gtk.Label('Freq (MHz): ')
        profile2_freq_label = gtk.Label('Freq (MHz): ')
        profile3_freq_label = gtk.Label('Freq (MHz): ')
        profile4_freq_label = gtk.Label('Freq (MHz): ')
        profile5_freq_label = gtk.Label('Freq (MHz): ')
        profile6_freq_label = gtk.Label('Freq (MHz): ')
        profile7_freq_label = gtk.Label('Freq (MHz): ')
        profile0_freq_adj = gtk.Adjustment(0.0, 0.0, 400.0, 0.000000001, 0.000000005, 0.0)
        profile1_freq_adj = gtk.Adjustment(0.0, 0.0, 400.0, 0.000000001, 0.000000005, 0.0)
        profile2_freq_adj = gtk.Adjustment(0.0, 0.0, 400.0, 0.000000001, 0.000000005, 0.0)
        profile3_freq_adj = gtk.Adjustment(0.0, 0.0, 400.0, 0.000000001, 0.000000005, 0.0)
        profile4_freq_adj = gtk.Adjustment(0.0, 0.0, 400.0, 0.000000001, 0.000000005, 0.0)
        profile5_freq_adj = gtk.Adjustment(0.0, 0.0, 400.0, 0.000000001, 0.000000005, 0.0)
        profile6_freq_adj = gtk.Adjustment(0.0, 0.0, 400.0, 0.000000001, 0.000000005, 0.0)
        profile7_freq_adj = gtk.Adjustment(0.0, 0.0, 400.0, 0.000000001, 0.000000005, 0.0)
        profile0_freq_spin = gtk.SpinButton(profile0_freq_adj, 0, 0)
        profile1_freq_spin = gtk.SpinButton(profile1_freq_adj, 0, 0)
        profile2_freq_spin = gtk.SpinButton(profile2_freq_adj, 0, 0)
        profile3_freq_spin = gtk.SpinButton(profile3_freq_adj, 0, 0)
        profile4_freq_spin = gtk.SpinButton(profile4_freq_adj, 0, 0)
        profile5_freq_spin = gtk.SpinButton(profile5_freq_adj, 0, 0)
        profile6_freq_spin = gtk.SpinButton(profile6_freq_adj, 0, 0)
        profile7_freq_spin = gtk.SpinButton(profile7_freq_adj, 0, 0)
        profile0_freq_spin.set_wrap(True)
        profile1_freq_spin.set_wrap(True)
        profile2_freq_spin.set_wrap(True)
        profile3_freq_spin.set_wrap(True)
        profile4_freq_spin.set_wrap(True)
        profile5_freq_spin.set_wrap(True)
        profile6_freq_spin.set_wrap(True)
        profile7_freq_spin.set_wrap(True)
        profile0_freq_spin.set_digits(9)
        profile1_freq_spin.set_digits(9)
        profile2_freq_spin.set_digits(9)
        profile3_freq_spin.set_digits(9)
        profile4_freq_spin.set_digits(9)
        profile5_freq_spin.set_digits(9)
        profile6_freq_spin.set_digits(9)
        profile7_freq_spin.set_digits(9)
        profile0_tuning_word_label = gtk.Label('Tuning Word Values: ')
        profile1_tuning_word_label = gtk.Label('Tuning Word Values: ')
        profile2_tuning_word_label = gtk.Label('Tuning Word Values: ')
        profile3_tuning_word_label = gtk.Label('Tuning Word Values: ')
        profile4_tuning_word_label = gtk.Label('Tuning Word Values: ')
        profile5_tuning_word_label = gtk.Label('Tuning Word Values: ')
        profile6_tuning_word_label = gtk.Label('Tuning Word Values: ')
        profile7_tuning_word_label = gtk.Label('Tuning Word Values: ')
        profile0_tuning_dec_label = gtk.Label('Dec')
        profile1_tuning_dec_label = gtk.Label('Dec')
        profile2_tuning_dec_label = gtk.Label('Dec')
        profile3_tuning_dec_label = gtk.Label('Dec')
        profile4_tuning_dec_label = gtk.Label('Dec')
        profile5_tuning_dec_label = gtk.Label('Dec')
        profile6_tuning_dec_label = gtk.Label('Dec')
        profile7_tuning_dec_label = gtk.Label('Dec')
        profile0_tuning_hex_label = gtk.Label('Hex')
        profile1_tuning_hex_label = gtk.Label('Hex')
        profile2_tuning_hex_label = gtk.Label('Hex')
        profile3_tuning_hex_label = gtk.Label('Hex')
        profile4_tuning_hex_label = gtk.Label('Hex')
        profile5_tuning_hex_label = gtk.Label('Hex')
        profile6_tuning_hex_label = gtk.Label('Hex')
        profile7_tuning_hex_label = gtk.Label('Hex')
        profile0_tuning_bin_label = gtk.Label('Bin')
        profile1_tuning_bin_label = gtk.Label('Bin')
        profile2_tuning_bin_label = gtk.Label('Bin')
        profile3_tuning_bin_label = gtk.Label('Bin')
        profile4_tuning_bin_label = gtk.Label('Bin')
        profile5_tuning_bin_label = gtk.Label('Bin')
        profile6_tuning_bin_label = gtk.Label('Bin')
        profile7_tuning_bin_label = gtk.Label('Bin')        
        profile0_tuning_dec_display = gtk.Entry()
        profile1_tuning_dec_display = gtk.Entry()
        profile2_tuning_dec_display = gtk.Entry()
        profile3_tuning_dec_display = gtk.Entry()
        profile4_tuning_dec_display = gtk.Entry()
        profile5_tuning_dec_display = gtk.Entry()
        profile6_tuning_dec_display = gtk.Entry()
        profile7_tuning_dec_display = gtk.Entry()
        profile0_tuning_dec_display.set_width_chars(10)
        profile1_tuning_dec_display.set_width_chars(10)
        profile2_tuning_dec_display.set_width_chars(10)
        profile3_tuning_dec_display.set_width_chars(10)
        profile4_tuning_dec_display.set_width_chars(10)
        profile5_tuning_dec_display.set_width_chars(10)
        profile6_tuning_dec_display.set_width_chars(10)
        profile7_tuning_dec_display.set_width_chars(10)
        profile0_tuning_hex_display = gtk.Entry()
        profile1_tuning_hex_display = gtk.Entry()
        profile2_tuning_hex_display = gtk.Entry()
        profile3_tuning_hex_display = gtk.Entry()
        profile4_tuning_hex_display = gtk.Entry()
        profile5_tuning_hex_display = gtk.Entry()
        profile6_tuning_hex_display = gtk.Entry()
        profile7_tuning_hex_display = gtk.Entry()
        profile0_tuning_hex_display.set_width_chars(8)
        profile1_tuning_hex_display.set_width_chars(8)
        profile2_tuning_hex_display.set_width_chars(8)
        profile3_tuning_hex_display.set_width_chars(8)
        profile4_tuning_hex_display.set_width_chars(8)
        profile5_tuning_hex_display.set_width_chars(8)
        profile6_tuning_hex_display.set_width_chars(8)
        profile7_tuning_hex_display.set_width_chars(8)        
        profile0_tuning_bin_display = gtk.Entry()
        profile1_tuning_bin_display = gtk.Entry()
        profile2_tuning_bin_display = gtk.Entry()
        profile3_tuning_bin_display = gtk.Entry()
        profile4_tuning_bin_display = gtk.Entry()
        profile5_tuning_bin_display = gtk.Entry()
        profile6_tuning_bin_display = gtk.Entry()
        profile7_tuning_bin_display = gtk.Entry()
        profile0_tuning_bin_display.set_width_chars(32)
        profile1_tuning_bin_display.set_width_chars(32)
        profile2_tuning_bin_display.set_width_chars(32)
        profile3_tuning_bin_display.set_width_chars(32)
        profile4_tuning_bin_display.set_width_chars(32)
        profile5_tuning_bin_display.set_width_chars(32)
        profile6_tuning_bin_display.set_width_chars(32)
        profile7_tuning_bin_display.set_width_chars(32)
        profile0_freq_frame = gtk.Frame('Output Frequency (Profile 0)')
        profile1_freq_frame = gtk.Frame('Output Frequency (Profile 1)')
        profile2_freq_frame = gtk.Frame('Output Frequency (Profile 2)')
        profile3_freq_frame = gtk.Frame('Output Frequency (Profile 3)')
        profile4_freq_frame = gtk.Frame('Output Frequency (Profile 4)')
        profile5_freq_frame = gtk.Frame('Output Frequency (Profile 5)')
        profile6_freq_frame = gtk.Frame('Output Frequency (Profile 6)')
        profile7_freq_frame = gtk.Frame('Output Frequency (Profile 7)')
        profile0_vbox.pack_start(profile0_freq_frame)
        profile1_vbox.pack_start(profile1_freq_frame)
        profile2_vbox.pack_start(profile2_freq_frame)
        profile3_vbox.pack_start(profile3_freq_frame)
        profile4_vbox.pack_start(profile4_freq_frame)
        profile5_vbox.pack_start(profile5_freq_frame)
        profile6_vbox.pack_start(profile6_freq_frame)
        profile7_vbox.pack_start(profile7_freq_frame)
        frame_vbox = gtk.VBox()
        profile0_freq_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile0_freq_label, False, False, 5)
        hbox.pack_start(profile0_freq_spin, False, False, 5)
        hbox.pack_start(profile0_tuning_word_label, False, False, 5)
        hbox.pack_start(profile0_tuning_dec_display, False, False, 5)
        hbox.pack_start(profile0_tuning_dec_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        hbox = gtk.HBox()
        hbox.pack_start(profile0_tuning_hex_display, False, False, 5)
        hbox.pack_start(profile0_tuning_hex_label, False, False, 5)        
        hbox.pack_start(profile0_tuning_bin_display, False, False, 5)
        hbox.pack_start(profile0_tuning_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        frame_vbox = gtk.VBox()
        profile1_freq_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile1_freq_label, False, False, 5)
        hbox.pack_start(profile1_freq_spin, False, False, 5)
        hbox.pack_start(profile1_tuning_word_label, False, False, 5)
        hbox.pack_start(profile1_tuning_dec_display, False, False, 5)
        hbox.pack_start(profile1_tuning_dec_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        hbox = gtk.HBox()
        hbox.pack_start(profile1_tuning_hex_display, False, False, 5)
        hbox.pack_start(profile1_tuning_hex_label, False, False, 5)        
        hbox.pack_start(profile1_tuning_bin_display, False, False, 5)
        hbox.pack_start(profile1_tuning_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        frame_vbox = gtk.VBox()
        profile2_freq_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile2_freq_label, False, False, 5)
        hbox.pack_start(profile2_freq_spin, False, False, 5)
        hbox.pack_start(profile2_tuning_word_label, False, False, 5)
        hbox.pack_start(profile2_tuning_dec_display, False, False, 5)
        hbox.pack_start(profile2_tuning_dec_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        hbox = gtk.HBox()
        hbox.pack_start(profile2_tuning_hex_display, False, False, 5)
        hbox.pack_start(profile2_tuning_hex_label, False, False, 5)        
        hbox.pack_start(profile2_tuning_bin_display, False, False, 5)
        hbox.pack_start(profile2_tuning_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        frame_vbox = gtk.VBox()
        profile3_freq_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile3_freq_label, False, False, 5)
        hbox.pack_start(profile3_freq_spin, False, False, 5)
        hbox.pack_start(profile3_tuning_word_label, False, False, 5)
        hbox.pack_start(profile3_tuning_dec_display, False, False, 5)
        hbox.pack_start(profile3_tuning_dec_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        hbox = gtk.HBox()
        hbox.pack_start(profile3_tuning_hex_display, False, False, 5)
        hbox.pack_start(profile3_tuning_hex_label, False, False, 5)        
        hbox.pack_start(profile3_tuning_bin_display, False, False, 5)
        hbox.pack_start(profile3_tuning_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        frame_vbox = gtk.VBox()
        profile4_freq_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile4_freq_label, False, False, 5)
        hbox.pack_start(profile4_freq_spin, False, False, 5)
        hbox.pack_start(profile4_tuning_word_label, False, False, 5)
        hbox.pack_start(profile4_tuning_dec_display, False, False, 5)
        hbox.pack_start(profile4_tuning_dec_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        hbox = gtk.HBox()
        hbox.pack_start(profile4_tuning_hex_display, False, False, 5)
        hbox.pack_start(profile4_tuning_hex_label, False, False, 5)        
        hbox.pack_start(profile4_tuning_bin_display, False, False, 5)
        hbox.pack_start(profile4_tuning_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        frame_vbox = gtk.VBox()
        profile5_freq_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile5_freq_label, False, False, 5)
        hbox.pack_start(profile5_freq_spin, False, False, 5)
        hbox.pack_start(profile5_tuning_word_label, False, False, 5)
        hbox.pack_start(profile5_tuning_dec_display, False, False, 5)
        hbox.pack_start(profile5_tuning_dec_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        hbox = gtk.HBox()
        hbox.pack_start(profile5_tuning_hex_display, False, False, 5)
        hbox.pack_start(profile5_tuning_hex_label, False, False, 5)        
        hbox.pack_start(profile5_tuning_bin_display, False, False, 5)
        hbox.pack_start(profile5_tuning_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        frame_vbox = gtk.VBox()
        profile6_freq_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile6_freq_label, False, False, 5)
        hbox.pack_start(profile6_freq_spin, False, False, 5)
        hbox.pack_start(profile6_tuning_word_label, False, False, 5)
        hbox.pack_start(profile6_tuning_dec_display, False, False, 5)
        hbox.pack_start(profile6_tuning_dec_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        hbox = gtk.HBox()
        hbox.pack_start(profile6_tuning_hex_display, False, False, 5)
        hbox.pack_start(profile6_tuning_hex_label, False, False, 5)        
        hbox.pack_start(profile6_tuning_bin_display, False, False, 5)
        hbox.pack_start(profile6_tuning_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        frame_vbox = gtk.VBox()
        profile7_freq_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile7_freq_label, False, False, 5)
        hbox.pack_start(profile7_freq_spin, False, False, 5)
        hbox.pack_start(profile7_tuning_word_label, False, False, 5)
        hbox.pack_start(profile7_tuning_dec_display, False, False, 5)
        hbox.pack_start(profile7_tuning_dec_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        hbox = gtk.HBox()
        hbox.pack_start(profile7_tuning_hex_display, False, False, 5)
        hbox.pack_start(profile7_tuning_hex_label, False, False, 5)        
        hbox.pack_start(profile7_tuning_bin_display, False, False, 5)
        hbox.pack_start(profile7_tuning_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        # Phase Offset Section
        profile0_phase_label = gtk.Label('Offset (Deg): ')
        profile1_phase_label = gtk.Label('Offset (Deg): ')
        profile2_phase_label = gtk.Label('Offset (Deg): ')
        profile3_phase_label = gtk.Label('Offset (Deg): ')
        profile4_phase_label = gtk.Label('Offset (Deg): ')
        profile5_phase_label = gtk.Label('Offset (Deg): ')
        profile6_phase_label = gtk.Label('Offset (Deg): ')
        profile7_phase_label = gtk.Label('Offset (Deg): ')
        profile0_phase_adj = gtk.Adjustment(0.0, 0.0, 360.0, 0.001, 0.005, 0.0)
        profile1_phase_adj = gtk.Adjustment(0.0, 0.0, 360.0, 0.001, 0.005, 0.0)
        profile2_phase_adj = gtk.Adjustment(0.0, 0.0, 360.0, 0.001, 0.005, 0.0)
        profile3_phase_adj = gtk.Adjustment(0.0, 0.0, 360.0, 0.001, 0.005, 0.0)
        profile4_phase_adj = gtk.Adjustment(0.0, 0.0, 360.0, 0.001, 0.005, 0.0)
        profile5_phase_adj = gtk.Adjustment(0.0, 0.0, 360.0, 0.001, 0.005, 0.0)
        profile6_phase_adj = gtk.Adjustment(0.0, 0.0, 360.0, 0.001, 0.005, 0.0)
        profile7_phase_adj = gtk.Adjustment(0.0, 0.0, 360.0, 0.001, 0.005, 0.0)
        profile0_phase_spin = gtk.SpinButton(profile0_phase_adj, 0, 0)
        profile1_phase_spin = gtk.SpinButton(profile1_phase_adj, 0, 0)
        profile2_phase_spin = gtk.SpinButton(profile2_phase_adj, 0, 0)
        profile3_phase_spin = gtk.SpinButton(profile3_phase_adj, 0, 0)
        profile4_phase_spin = gtk.SpinButton(profile4_phase_adj, 0, 0)
        profile5_phase_spin = gtk.SpinButton(profile5_phase_adj, 0, 0)
        profile6_phase_spin = gtk.SpinButton(profile6_phase_adj, 0, 0)
        profile7_phase_spin = gtk.SpinButton(profile7_phase_adj, 0, 0)
        profile0_phase_spin.set_wrap(True)
        profile1_phase_spin.set_wrap(True)
        profile2_phase_spin.set_wrap(True)
        profile3_phase_spin.set_wrap(True)
        profile4_phase_spin.set_wrap(True)
        profile5_phase_spin.set_wrap(True)
        profile6_phase_spin.set_wrap(True)
        profile7_phase_spin.set_wrap(True)
        profile0_phase_spin.set_digits(3)
        profile1_phase_spin.set_digits(3)
        profile2_phase_spin.set_digits(3)
        profile3_phase_spin.set_digits(3)
        profile4_phase_spin.set_digits(3)
        profile5_phase_spin.set_digits(3)
        profile6_phase_spin.set_digits(3)
        profile7_phase_spin.set_digits(3)
        profile0_phase_word_label = gtk.Label('Register Values: ')
        profile1_phase_word_label = gtk.Label('Register Values: ')
        profile2_phase_word_label = gtk.Label('Register Values: ')
        profile3_phase_word_label = gtk.Label('Register Values: ')
        profile4_phase_word_label = gtk.Label('Register Values: ')
        profile5_phase_word_label = gtk.Label('Register Values: ')
        profile6_phase_word_label = gtk.Label('Register Values: ')
        profile7_phase_word_label = gtk.Label('Register Values: ')
        profile0_phase_dec_label = gtk.Label('Dec')
        profile1_phase_dec_label = gtk.Label('Dec')
        profile2_phase_dec_label = gtk.Label('Dec')
        profile3_phase_dec_label = gtk.Label('Dec')
        profile4_phase_dec_label = gtk.Label('Dec')
        profile5_phase_dec_label = gtk.Label('Dec')
        profile6_phase_dec_label = gtk.Label('Dec')
        profile7_phase_dec_label = gtk.Label('Dec')
        profile0_phase_hex_label = gtk.Label('Hex')
        profile1_phase_hex_label = gtk.Label('Hex')
        profile2_phase_hex_label = gtk.Label('Hex')
        profile3_phase_hex_label = gtk.Label('Hex')
        profile4_phase_hex_label = gtk.Label('Hex')
        profile5_phase_hex_label = gtk.Label('Hex')
        profile6_phase_hex_label = gtk.Label('Hex')
        profile7_phase_hex_label = gtk.Label('Hex')
        profile0_phase_bin_label = gtk.Label('Bin')
        profile1_phase_bin_label = gtk.Label('Bin')
        profile2_phase_bin_label = gtk.Label('Bin')
        profile3_phase_bin_label = gtk.Label('Bin')
        profile4_phase_bin_label = gtk.Label('Bin')
        profile5_phase_bin_label = gtk.Label('Bin')
        profile6_phase_bin_label = gtk.Label('Bin')
        profile7_phase_bin_label = gtk.Label('Bin')        
        profile0_phase_dec_display = gtk.Entry()
        profile1_phase_dec_display = gtk.Entry()
        profile2_phase_dec_display = gtk.Entry()
        profile3_phase_dec_display = gtk.Entry()
        profile4_phase_dec_display = gtk.Entry()
        profile5_phase_dec_display = gtk.Entry()
        profile6_phase_dec_display = gtk.Entry()
        profile7_phase_dec_display = gtk.Entry()
        profile0_phase_dec_display.set_width_chars(5)
        profile1_phase_dec_display.set_width_chars(5)
        profile2_phase_dec_display.set_width_chars(5)
        profile3_phase_dec_display.set_width_chars(5)
        profile4_phase_dec_display.set_width_chars(5)
        profile5_phase_dec_display.set_width_chars(5)
        profile6_phase_dec_display.set_width_chars(5)
        profile7_phase_dec_display.set_width_chars(5)
        profile0_phase_hex_display = gtk.Entry()
        profile1_phase_hex_display = gtk.Entry()
        profile2_phase_hex_display = gtk.Entry()
        profile3_phase_hex_display = gtk.Entry()
        profile4_phase_hex_display = gtk.Entry()
        profile5_phase_hex_display = gtk.Entry()
        profile6_phase_hex_display = gtk.Entry()
        profile7_phase_hex_display = gtk.Entry()
        profile0_phase_hex_display.set_width_chars(4)
        profile1_phase_hex_display.set_width_chars(4)
        profile2_phase_hex_display.set_width_chars(4)
        profile3_phase_hex_display.set_width_chars(4)
        profile4_phase_hex_display.set_width_chars(4)
        profile5_phase_hex_display.set_width_chars(4)
        profile6_phase_hex_display.set_width_chars(4)
        profile7_phase_hex_display.set_width_chars(4)        
        profile0_phase_bin_display = gtk.Entry()
        profile1_phase_bin_display = gtk.Entry()
        profile2_phase_bin_display = gtk.Entry()
        profile3_phase_bin_display = gtk.Entry()
        profile4_phase_bin_display = gtk.Entry()
        profile5_phase_bin_display = gtk.Entry()
        profile6_phase_bin_display = gtk.Entry()
        profile7_phase_bin_display = gtk.Entry()
        profile0_phase_bin_display.set_width_chars(16)
        profile1_phase_bin_display.set_width_chars(16)
        profile2_phase_bin_display.set_width_chars(16)
        profile3_phase_bin_display.set_width_chars(16)
        profile4_phase_bin_display.set_width_chars(16)
        profile5_phase_bin_display.set_width_chars(16)
        profile6_phase_bin_display.set_width_chars(16)
        profile7_phase_bin_display.set_width_chars(16)
        profile0_phase_frame = gtk.Frame('Phase Offset')
        profile1_phase_frame = gtk.Frame('Phase Offset')
        profile2_phase_frame = gtk.Frame('Phase Offset')
        profile3_phase_frame = gtk.Frame('Phase Offset')
        profile4_phase_frame = gtk.Frame('Phase Offset')
        profile5_phase_frame = gtk.Frame('Phase Offset')
        profile6_phase_frame = gtk.Frame('Phase Offset')
        profile7_phase_frame = gtk.Frame('Phase Offset')
        profile0_vbox.pack_start(profile0_phase_frame)
        profile1_vbox.pack_start(profile1_phase_frame)
        profile2_vbox.pack_start(profile2_phase_frame)
        profile3_vbox.pack_start(profile3_phase_frame)
        profile4_vbox.pack_start(profile4_phase_frame)
        profile5_vbox.pack_start(profile5_phase_frame)
        profile6_vbox.pack_start(profile6_phase_frame)
        profile7_vbox.pack_start(profile7_phase_frame)
        frame_vbox = gtk.VBox()
        profile0_phase_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile0_phase_label, False, False)
        hbox.pack_start(profile0_phase_spin, False, False, 5)
        hbox.pack_start(profile0_phase_word_label, False, False)
        hbox.pack_start(profile0_phase_dec_display, False, False, 5)
        hbox.pack_start(profile0_phase_dec_label, False, False, 5)
        hbox.pack_start(profile0_phase_hex_display, False, False, 5)
        hbox.pack_start(profile0_phase_hex_label, False, False, 5)
        hbox.pack_start(profile0_phase_bin_display, False, False, 5)
        hbox.pack_start(profile0_phase_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)        
        frame_vbox = gtk.VBox()
        profile1_phase_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile1_phase_label, False, False)
        hbox.pack_start(profile1_phase_spin, False, False, 5)
        hbox.pack_start(profile1_phase_word_label, False, False)
        hbox.pack_start(profile1_phase_dec_display, False, False, 5)
        hbox.pack_start(profile1_phase_dec_label, False, False, 5)
        hbox.pack_start(profile1_phase_hex_display, False, False, 5)
        hbox.pack_start(profile1_phase_hex_label, False, False, 5)
        hbox.pack_start(profile1_phase_bin_display, False, False, 5)
        hbox.pack_start(profile1_phase_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)        
        frame_vbox = gtk.VBox()
        profile2_phase_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile2_phase_label, False, False)
        hbox.pack_start(profile2_phase_spin, False, False, 5)
        hbox.pack_start(profile2_phase_word_label, False, False)
        hbox.pack_start(profile2_phase_dec_display, False, False, 5)
        hbox.pack_start(profile2_phase_dec_label, False, False, 5)
        hbox.pack_start(profile2_phase_hex_display, False, False, 5)
        hbox.pack_start(profile2_phase_hex_label, False, False, 5)
        hbox.pack_start(profile2_phase_bin_display, False, False, 5)
        hbox.pack_start(profile2_phase_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)        
        frame_vbox = gtk.VBox()
        profile3_phase_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile3_phase_label, False, False)
        hbox.pack_start(profile3_phase_spin, False, False, 5)
        hbox.pack_start(profile3_phase_word_label, False, False)
        hbox.pack_start(profile3_phase_dec_display, False, False, 5)
        hbox.pack_start(profile3_phase_dec_label, False, False, 5)
        hbox.pack_start(profile3_phase_hex_display, False, False, 5)
        hbox.pack_start(profile3_phase_hex_label, False, False, 5)
        hbox.pack_start(profile3_phase_bin_display, False, False, 5)
        hbox.pack_start(profile3_phase_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)        
        frame_vbox = gtk.VBox()
        profile4_phase_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile4_phase_label, False, False)
        hbox.pack_start(profile4_phase_spin, False, False, 5)
        hbox.pack_start(profile4_phase_word_label, False, False)
        hbox.pack_start(profile4_phase_dec_display, False, False, 5)
        hbox.pack_start(profile4_phase_dec_label, False, False, 5)
        hbox.pack_start(profile4_phase_hex_display, False, False, 5)
        hbox.pack_start(profile4_phase_hex_label, False, False, 5)
        hbox.pack_start(profile4_phase_bin_display, False, False, 5)
        hbox.pack_start(profile4_phase_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)        
        frame_vbox = gtk.VBox()
        profile5_phase_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile5_phase_label, False, False)
        hbox.pack_start(profile5_phase_spin, False, False, 5)
        hbox.pack_start(profile5_phase_word_label, False, False)
        hbox.pack_start(profile5_phase_dec_display, False, False, 5)
        hbox.pack_start(profile5_phase_dec_label, False, False, 5)
        hbox.pack_start(profile5_phase_hex_display, False, False, 5)
        hbox.pack_start(profile5_phase_hex_label, False, False, 5)
        hbox.pack_start(profile5_phase_bin_display, False, False, 5)
        hbox.pack_start(profile5_phase_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)        
        frame_vbox = gtk.VBox()
        profile6_phase_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile6_phase_label, False, False)
        hbox.pack_start(profile6_phase_spin, False, False, 5)
        hbox.pack_start(profile6_phase_word_label, False, False)
        hbox.pack_start(profile6_phase_dec_display, False, False, 5)
        hbox.pack_start(profile6_phase_dec_label, False, False, 5)
        hbox.pack_start(profile6_phase_hex_display, False, False, 5)
        hbox.pack_start(profile6_phase_hex_label, False, False, 5)
        hbox.pack_start(profile6_phase_bin_display, False, False, 5)
        hbox.pack_start(profile6_phase_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)        
        frame_vbox = gtk.VBox()
        profile7_phase_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile7_phase_label, False, False)
        hbox.pack_start(profile7_phase_spin, False, False, 5)
        hbox.pack_start(profile7_phase_word_label, False, False)
        hbox.pack_start(profile7_phase_dec_display, False, False, 5)
        hbox.pack_start(profile7_phase_dec_label, False, False, 5)
        hbox.pack_start(profile7_phase_hex_display, False, False, 5)
        hbox.pack_start(profile7_phase_hex_label, False, False, 5)
        hbox.pack_start(profile7_phase_bin_display, False, False, 5)
        hbox.pack_start(profile7_phase_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)
        # Output Scale Factor Section
        profile0_scale_label = gtk.Label('Output SF: ')
        profile1_scale_label = gtk.Label('Output SF: ')
        profile2_scale_label = gtk.Label('Output SF: ')
        profile3_scale_label = gtk.Label('Output SF: ')
        profile4_scale_label = gtk.Label('Output SF: ')
        profile5_scale_label = gtk.Label('Output SF: ')
        profile6_scale_label = gtk.Label('Output SF: ')
        profile7_scale_label = gtk.Label('Output SF: ')
        profile0_sf_adj = gtk.Adjustment(0.00000, 0.00000, 1.00000, 0.00001, 0.00005, 0.0)
        profile1_sf_adj = gtk.Adjustment(0.00000, 0.00000, 1.00000, 0.00001, 0.00005, 0.0)
        profile2_sf_adj = gtk.Adjustment(0.00000, 0.00000, 1.00000, 0.00001, 0.00005, 0.0)
        profile3_sf_adj = gtk.Adjustment(0.00000, 0.00000, 1.00000, 0.00001, 0.00005, 0.0)
        profile4_sf_adj = gtk.Adjustment(0.00000, 0.00000, 1.00000, 0.00001, 0.00005, 0.0)
        profile5_sf_adj = gtk.Adjustment(0.00000, 0.00000, 1.00000, 0.00001, 0.00005, 0.0)
        profile6_sf_adj = gtk.Adjustment(0.00000, 0.00000, 1.00000, 0.00001, 0.00005, 0.0)
        profile7_sf_adj = gtk.Adjustment(0.00000, 0.00000, 1.00000, 0.00001, 0.00005, 0.0)
        profile0_scale_spin = gtk.SpinButton(profile0_sf_adj, 0, 0)
        profile1_scale_spin = gtk.SpinButton(profile1_sf_adj, 0, 0)
        profile2_scale_spin = gtk.SpinButton(profile2_sf_adj, 0, 0)
        profile3_scale_spin = gtk.SpinButton(profile3_sf_adj, 0, 0)
        profile4_scale_spin = gtk.SpinButton(profile4_sf_adj, 0, 0)
        profile5_scale_spin = gtk.SpinButton(profile5_sf_adj, 0, 0)
        profile6_scale_spin = gtk.SpinButton(profile6_sf_adj, 0, 0)
        profile7_scale_spin = gtk.SpinButton(profile7_sf_adj, 0, 0)
        profile0_scale_spin.set_wrap(True)
        profile1_scale_spin.set_wrap(True)
        profile2_scale_spin.set_wrap(True)
        profile3_scale_spin.set_wrap(True)
        profile4_scale_spin.set_wrap(True)
        profile5_scale_spin.set_wrap(True)
        profile6_scale_spin.set_wrap(True)
        profile7_scale_spin.set_wrap(True)
        profile0_scale_spin.set_digits(5)
        profile1_scale_spin.set_digits(5)
        profile2_scale_spin.set_digits(5)
        profile3_scale_spin.set_digits(5)
        profile4_scale_spin.set_digits(5)
        profile5_scale_spin.set_digits(5)
        profile6_scale_spin.set_digits(5)
        profile7_scale_spin.set_digits(5)
        profile0_scale_word_label = gtk.Label('Register Values: ')
        profile1_scale_word_label = gtk.Label('Register Values: ')
        profile2_scale_word_label = gtk.Label('Register Values: ')
        profile3_scale_word_label = gtk.Label('Register Values: ')
        profile4_scale_word_label = gtk.Label('Register Values: ')
        profile5_scale_word_label = gtk.Label('Register Values: ')
        profile6_scale_word_label = gtk.Label('Register Values: ')
        profile7_scale_word_label = gtk.Label('Register Values: ')
        profile0_scale_dec_label = gtk.Label('Dec')
        profile1_scale_dec_label = gtk.Label('Dec')
        profile2_scale_dec_label = gtk.Label('Dec')
        profile3_scale_dec_label = gtk.Label('Dec')
        profile4_scale_dec_label = gtk.Label('Dec')
        profile5_scale_dec_label = gtk.Label('Dec')
        profile6_scale_dec_label = gtk.Label('Dec')
        profile7_scale_dec_label = gtk.Label('Dec')
        profile0_scale_hex_label = gtk.Label('Hex')
        profile1_scale_hex_label = gtk.Label('Hex')
        profile2_scale_hex_label = gtk.Label('Hex')
        profile3_scale_hex_label = gtk.Label('Hex')
        profile4_scale_hex_label = gtk.Label('Hex')
        profile5_scale_hex_label = gtk.Label('Hex')
        profile6_scale_hex_label = gtk.Label('Hex')
        profile7_scale_hex_label = gtk.Label('Hex')
        profile0_scale_bin_label = gtk.Label('Bin')
        profile1_scale_bin_label = gtk.Label('Bin')
        profile2_scale_bin_label = gtk.Label('Bin')
        profile3_scale_bin_label = gtk.Label('Bin')
        profile4_scale_bin_label = gtk.Label('Bin')
        profile5_scale_bin_label = gtk.Label('Bin')
        profile6_scale_bin_label = gtk.Label('Bin')
        profile7_scale_bin_label = gtk.Label('Bin')        
        profile0_scale_dec_display = gtk.Entry()
        profile1_scale_dec_display = gtk.Entry()
        profile2_scale_dec_display = gtk.Entry()
        profile3_scale_dec_display = gtk.Entry()
        profile4_scale_dec_display = gtk.Entry()
        profile5_scale_dec_display = gtk.Entry()
        profile6_scale_dec_display = gtk.Entry()
        profile7_scale_dec_display = gtk.Entry()
        profile0_scale_dec_display.set_width_chars(5)
        profile1_scale_dec_display.set_width_chars(5)
        profile2_scale_dec_display.set_width_chars(5)
        profile3_scale_dec_display.set_width_chars(5)
        profile4_scale_dec_display.set_width_chars(5)
        profile5_scale_dec_display.set_width_chars(5)
        profile6_scale_dec_display.set_width_chars(5)
        profile7_scale_dec_display.set_width_chars(5)
        profile0_scale_hex_display = gtk.Entry()
        profile1_scale_hex_display = gtk.Entry()
        profile2_scale_hex_display = gtk.Entry()
        profile3_scale_hex_display = gtk.Entry()
        profile4_scale_hex_display = gtk.Entry()
        profile5_scale_hex_display = gtk.Entry()
        profile6_scale_hex_display = gtk.Entry()
        profile7_scale_hex_display = gtk.Entry()
        profile0_scale_hex_display.set_width_chars(4)
        profile1_scale_hex_display.set_width_chars(4)
        profile2_scale_hex_display.set_width_chars(4)
        profile3_scale_hex_display.set_width_chars(4)
        profile4_scale_hex_display.set_width_chars(4)
        profile5_scale_hex_display.set_width_chars(4)
        profile6_scale_hex_display.set_width_chars(4)
        profile7_scale_hex_display.set_width_chars(4)        
        profile0_scale_bin_display = gtk.Entry()
        profile1_scale_bin_display = gtk.Entry()
        profile2_scale_bin_display = gtk.Entry()
        profile3_scale_bin_display = gtk.Entry()
        profile4_scale_bin_display = gtk.Entry()
        profile5_scale_bin_display = gtk.Entry()
        profile6_scale_bin_display = gtk.Entry()
        profile7_scale_bin_display = gtk.Entry()
        profile0_scale_bin_display.set_width_chars(14)
        profile1_scale_bin_display.set_width_chars(14)
        profile2_scale_bin_display.set_width_chars(14)
        profile3_scale_bin_display.set_width_chars(14)
        profile4_scale_bin_display.set_width_chars(14)
        profile5_scale_bin_display.set_width_chars(14)
        profile6_scale_bin_display.set_width_chars(14)
        profile7_scale_bin_display.set_width_chars(14)
        profile0_scale_frame = gtk.Frame('Output Scale Factor')
        profile1_scale_frame = gtk.Frame('Output Scale Factor')
        profile2_scale_frame = gtk.Frame('Output Scale Factor')
        profile3_scale_frame = gtk.Frame('Output Scale Factor')
        profile4_scale_frame = gtk.Frame('Output Scale Factor')
        profile5_scale_frame = gtk.Frame('Output Scale Factor')
        profile6_scale_frame = gtk.Frame('Output Scale Factor')
        profile7_scale_frame = gtk.Frame('Output Scale Factor')
        profile0_vbox.pack_start(profile0_scale_frame)
        profile1_vbox.pack_start(profile1_scale_frame)
        profile2_vbox.pack_start(profile2_scale_frame)
        profile3_vbox.pack_start(profile3_scale_frame)
        profile4_vbox.pack_start(profile4_scale_frame)
        profile5_vbox.pack_start(profile5_scale_frame)
        profile6_vbox.pack_start(profile6_scale_frame)
        profile7_vbox.pack_start(profile7_scale_frame)
        frame_vbox = gtk.VBox()
        profile0_scale_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile0_scale_label, False, False, 5)
        hbox.pack_start(profile0_scale_spin, False, False, 5)
        hbox.pack_start(profile0_scale_word_label, False, False, 5)
        hbox.pack_start(profile0_scale_dec_display, False, False, 5)
        hbox.pack_start(profile0_scale_dec_label, False, False, 5)
        hbox.pack_start(profile0_scale_hex_display, False, False, 5)
        hbox.pack_start(profile0_scale_hex_label, False, False, 5)
        hbox.pack_start(profile0_scale_bin_display, False, False, 5)
        hbox.pack_start(profile0_scale_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)        
        frame_vbox = gtk.VBox()
        profile1_scale_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile1_scale_label, False, False, 5)
        hbox.pack_start(profile1_scale_spin, False, False, 5)
        hbox.pack_start(profile1_scale_word_label, False, False, 5)
        hbox.pack_start(profile1_scale_dec_display, False, False, 5)
        hbox.pack_start(profile1_scale_dec_label, False, False, 5)
        hbox.pack_start(profile1_scale_hex_display, False, False, 5)
        hbox.pack_start(profile1_scale_hex_label, False, False, 5)
        hbox.pack_start(profile1_scale_bin_display, False, False, 5)
        hbox.pack_start(profile1_scale_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)        
        frame_vbox = gtk.VBox()
        profile2_scale_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile2_scale_label, False, False, 5)
        hbox.pack_start(profile2_scale_spin, False, False, 5)
        hbox.pack_start(profile2_scale_word_label, False, False, 5)
        hbox.pack_start(profile2_scale_dec_display, False, False, 5)
        hbox.pack_start(profile2_scale_dec_label, False, False, 5)
        hbox.pack_start(profile2_scale_hex_display, False, False, 5)
        hbox.pack_start(profile2_scale_hex_label, False, False, 5)
        hbox.pack_start(profile2_scale_bin_display, False, False, 5)
        hbox.pack_start(profile2_scale_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)        
        frame_vbox = gtk.VBox()
        profile3_scale_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile3_scale_label, False, False, 5)
        hbox.pack_start(profile3_scale_spin, False, False, 5)
        hbox.pack_start(profile3_scale_word_label, False, False, 5)
        hbox.pack_start(profile3_scale_dec_display, False, False, 5)
        hbox.pack_start(profile3_scale_dec_label, False, False, 5)
        hbox.pack_start(profile3_scale_hex_display, False, False, 5)
        hbox.pack_start(profile3_scale_hex_label, False, False, 5)
        hbox.pack_start(profile3_scale_bin_display, False, False, 5)
        hbox.pack_start(profile3_scale_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)        
        frame_vbox = gtk.VBox()
        profile4_scale_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile4_scale_label, False, False, 5)
        hbox.pack_start(profile4_scale_spin, False, False, 5)
        hbox.pack_start(profile4_scale_word_label, False, False, 5)
        hbox.pack_start(profile4_scale_dec_display, False, False, 5)
        hbox.pack_start(profile4_scale_dec_label, False, False, 5)
        hbox.pack_start(profile4_scale_hex_display, False, False, 5)
        hbox.pack_start(profile4_scale_hex_label, False, False, 5)
        hbox.pack_start(profile4_scale_bin_display, False, False, 5)
        hbox.pack_start(profile4_scale_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)        
        frame_vbox = gtk.VBox()
        profile5_scale_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile5_scale_label, False, False, 5)
        hbox.pack_start(profile5_scale_spin, False, False, 5)
        hbox.pack_start(profile5_scale_word_label, False, False, 5)
        hbox.pack_start(profile5_scale_dec_display, False, False, 5)
        hbox.pack_start(profile5_scale_dec_label, False, False, 5)
        hbox.pack_start(profile5_scale_hex_display, False, False, 5)
        hbox.pack_start(profile5_scale_hex_label, False, False, 5)
        hbox.pack_start(profile5_scale_bin_display, False, False, 5)
        hbox.pack_start(profile5_scale_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)        
        frame_vbox = gtk.VBox()
        profile6_scale_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile6_scale_label, False, False, 5)
        hbox.pack_start(profile6_scale_spin, False, False, 5)
        hbox.pack_start(profile6_scale_word_label, False, False, 5)
        hbox.pack_start(profile6_scale_dec_display, False, False, 5)
        hbox.pack_start(profile6_scale_dec_label, False, False, 5)
        hbox.pack_start(profile6_scale_hex_display, False, False, 5)
        hbox.pack_start(profile6_scale_hex_label, False, False, 5)
        hbox.pack_start(profile6_scale_bin_display, False, False, 5)
        hbox.pack_start(profile6_scale_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)        
        frame_vbox = gtk.VBox()
        profile7_scale_frame.add(frame_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(profile7_scale_label, False, False, 5)
        hbox.pack_start(profile7_scale_spin, False, False, 5)
        hbox.pack_start(profile7_scale_word_label, False, False, 5)
        hbox.pack_start(profile7_scale_dec_display, False, False, 5)
        hbox.pack_start(profile7_scale_dec_label, False, False, 5)
        hbox.pack_start(profile7_scale_hex_display, False, False, 5)
        hbox.pack_start(profile7_scale_hex_label, False, False, 5)
        hbox.pack_start(profile7_scale_bin_display, False, False, 5)
        hbox.pack_start(profile7_scale_bin_label, False, False, 5)
        frame_vbox.pack_start(hbox, False, False, 5)

        # RAM I/O section
        ram_notebook = gtk.Notebook()
        ram_notebook.show()
        ram_notebook.set_tab_pos(gtk.POS_BOTTOM)
        ram0_vbox = gtk.VBox()
        ram0_vbox.show()
        ram0_vbox.set_border_width(10)
        ram1_vbox = gtk.VBox()
        ram1_vbox.show()
        ram1_vbox.set_border_width(10)
        ram2_vbox = gtk.VBox()
        ram2_vbox.show()
        ram2_vbox.set_border_width(10)
        ram3_vbox = gtk.VBox()
        ram3_vbox.show()
        ram3_vbox.set_border_width(10)
        ram4_vbox = gtk.VBox()
        ram4_vbox.show()
        ram4_vbox.set_border_width(10)
        ram5_vbox = gtk.VBox()
        ram5_vbox.show()
        ram5_vbox.set_border_width(10)
        ram6_vbox = gtk.VBox()
        ram6_vbox.show()
        ram6_vbox.set_border_width(10)
        ram7_vbox = gtk.VBox()
        ram7_vbox.show()
        ram7_vbox.set_border_width(10)
        # Frames
        ram0_frame = gtk.Frame('RAM (Profile 0)')
        ram1_frame = gtk.Frame('RAM (Profile 1)')
        ram2_frame = gtk.Frame('RAM (Profile 2)')
        ram3_frame = gtk.Frame('RAM (Profile 3)')
        ram4_frame = gtk.Frame('RAM (Profile 4)')
        ram5_frame = gtk.Frame('RAM (Profile 5)')
        ram6_frame = gtk.Frame('RAM (Profile 6)')
        ram7_frame = gtk.Frame('RAM (Profile 7)')
        ram0_frame.show()
        ram1_frame.show()
        ram2_frame.show()
        ram3_frame.show()
        ram4_frame.show()
        ram5_frame.show()
        ram6_frame.show()
        ram7_frame.show()
        ram0_frame.add(ram0_vbox)
        ram1_frame.add(ram1_vbox)
        ram2_frame.add(ram2_vbox)
        ram3_frame.add(ram3_vbox)
        ram4_frame.add(ram4_vbox)
        ram5_frame.add(ram5_vbox)
        ram6_frame.add(ram6_vbox)
        ram7_frame.add(ram7_vbox)
        # Add Tabbed Windows to Notebook
        ram_notebook.add(ram0_frame)
        ram_notebook.add(ram1_frame)
        ram_notebook.add(ram2_frame)
        ram_notebook.add(ram3_frame)
        ram_notebook.add(ram4_frame)
        ram_notebook.add(ram5_frame)
        ram_notebook.add(ram6_frame)
        ram_notebook.add(ram7_frame)
        # Widgets
        ram0_label = gtk.Label('Ram 0')
        ram1_label = gtk.Label('Ram 1')
        ram2_label = gtk.Label('Ram 2')
        ram3_label = gtk.Label('Ram 3')
        ram4_label = gtk.Label('Ram 4')
        ram5_label = gtk.Label('Ram 5')
        ram6_label = gtk.Label('Ram 6')
        ram7_label = gtk.Label('Ram 7')
        ram_notebook.set_tab_label(ram_notebook.get_nth_page(0), ram0_label)
        ram_notebook.set_tab_label(ram_notebook.get_nth_page(1), ram1_label)
        ram_notebook.set_tab_label(ram_notebook.get_nth_page(2), ram2_label)
        ram_notebook.set_tab_label(ram_notebook.get_nth_page(3), ram3_label)
        ram_notebook.set_tab_label(ram_notebook.get_nth_page(4), ram4_label)        
        ram_notebook.set_tab_label(ram_notebook.get_nth_page(5), ram5_label)
        ram_notebook.set_tab_label(ram_notebook.get_nth_page(6), ram6_label)
        ram_notebook.set_tab_label(ram_notebook.get_nth_page(7), ram7_label)

        ram0_begin_addr_label = gtk.Label('Beginning Address: ')
        ram1_begin_addr_label = gtk.Label('Beginning Address: ')
        ram2_begin_addr_label = gtk.Label('Beginning Address: ')
        ram3_begin_addr_label = gtk.Label('Beginning Address: ')
        ram4_begin_addr_label = gtk.Label('Beginning Address: ')
        ram5_begin_addr_label = gtk.Label('Beginning Address: ')
        ram6_begin_addr_label = gtk.Label('Beginning Address: ')
        ram7_begin_addr_label = gtk.Label('Beginning Address: ')
        ram0_begin_addr_label.show()
        ram1_begin_addr_label.show()
        ram2_begin_addr_label.show()
        ram3_begin_addr_label.show()
        ram4_begin_addr_label.show()
        ram5_begin_addr_label.show()
        ram6_begin_addr_label.show()
        ram7_begin_addr_label.show()
        ram0_begin_addr_display = gtk.Entry()
        ram1_begin_addr_display = gtk.Entry()
        ram2_begin_addr_display = gtk.Entry()
        ram3_begin_addr_display = gtk.Entry()
        ram4_begin_addr_display = gtk.Entry()
        ram5_begin_addr_display = gtk.Entry()
        ram6_begin_addr_display = gtk.Entry()
        ram7_begin_addr_display = gtk.Entry()
        ram0_begin_addr_display.show()
        ram1_begin_addr_display.show()
        ram2_begin_addr_display.show()
        ram3_begin_addr_display.show()
        ram4_begin_addr_display.show()
        ram5_begin_addr_display.show()
        ram6_begin_addr_display.show()
        ram7_begin_addr_display.show()
        ram0_begin_addr_display.set_width_chars(4)
        ram1_begin_addr_display.set_width_chars(4)
        ram2_begin_addr_display.set_width_chars(4)
        ram3_begin_addr_display.set_width_chars(4)
        ram4_begin_addr_display.set_width_chars(4)
        ram5_begin_addr_display.set_width_chars(4)
        ram6_begin_addr_display.set_width_chars(4)
        ram7_begin_addr_display.set_width_chars(4)
        ram0_final_addr_label = gtk.Label('Final Address: ')
        ram1_final_addr_label = gtk.Label('Final Address: ')
        ram2_final_addr_label = gtk.Label('Final Address: ')
        ram3_final_addr_label = gtk.Label('Final Address: ')
        ram4_final_addr_label = gtk.Label('Final Address: ')
        ram5_final_addr_label = gtk.Label('Final Address: ')
        ram6_final_addr_label = gtk.Label('Final Address: ')
        ram7_final_addr_label = gtk.Label('Final Address: ')
        ram0_final_addr_label.show()
        ram1_final_addr_label.show()
        ram2_final_addr_label.show()
        ram3_final_addr_label.show()
        ram4_final_addr_label.show()
        ram5_final_addr_label.show()
        ram6_final_addr_label.show()
        ram7_final_addr_label.show()
        ram0_final_addr_display = gtk.Entry()
        ram1_final_addr_display = gtk.Entry()
        ram2_final_addr_display = gtk.Entry()
        ram3_final_addr_display = gtk.Entry()
        ram4_final_addr_display = gtk.Entry()
        ram5_final_addr_display = gtk.Entry()
        ram6_final_addr_display = gtk.Entry()
        ram7_final_addr_display = gtk.Entry()
        ram0_final_addr_display.show()
        ram1_final_addr_display.show()
        ram2_final_addr_display.show()
        ram3_final_addr_display.show()
        ram4_final_addr_display.show()
        ram5_final_addr_display.show()
        ram6_final_addr_display.show()
        ram7_final_addr_display.show()
        ram0_final_addr_display.set_width_chars(4)
        ram1_final_addr_display.set_width_chars(4)
        ram2_final_addr_display.set_width_chars(4)
        ram3_final_addr_display.set_width_chars(4)
        ram4_final_addr_display.set_width_chars(4)
        ram5_final_addr_display.set_width_chars(4)
        ram6_final_addr_display.set_width_chars(4)
        ram7_final_addr_display.set_width_chars(4)
        ram0_addr_step_rate_label = gtk.Label('Address Step Rate: ')
        ram1_addr_step_rate_label = gtk.Label('Address Step Rate: ')
        ram2_addr_step_rate_label = gtk.Label('Address Step Rate: ')
        ram3_addr_step_rate_label = gtk.Label('Address Step Rate: ')
        ram4_addr_step_rate_label = gtk.Label('Address Step Rate: ')
        ram5_addr_step_rate_label = gtk.Label('Address Step Rate: ')
        ram6_addr_step_rate_label = gtk.Label('Address Step Rate: ')
        ram7_addr_step_rate_label = gtk.Label('Address Step Rate: ')
        ram0_addr_step_rate_label.show()
        ram1_addr_step_rate_label.show()
        ram2_addr_step_rate_label.show()
        ram3_addr_step_rate_label.show()
        ram4_addr_step_rate_label.show()
        ram5_addr_step_rate_label.show()
        ram6_addr_step_rate_label.show()
        ram7_addr_step_rate_label.show()
        ram0_addr_step_rate_adj = gtk.Adjustment(0.0, 0.0, 65535.0, 1.0, 5.0, 0.0)
        ram1_addr_step_rate_adj = gtk.Adjustment(0.0, 0.0, 65535.0, 1.0, 5.0, 0.0)
        ram2_addr_step_rate_adj = gtk.Adjustment(0.0, 0.0, 65535.0, 1.0, 5.0, 0.0)
        ram3_addr_step_rate_adj = gtk.Adjustment(0.0, 0.0, 65535.0, 1.0, 5.0, 0.0)
        ram4_addr_step_rate_adj = gtk.Adjustment(0.0, 0.0, 65535.0, 1.0, 5.0, 0.0)
        ram5_addr_step_rate_adj = gtk.Adjustment(0.0, 0.0, 65535.0, 1.0, 5.0, 0.0)
        ram6_addr_step_rate_adj = gtk.Adjustment(0.0, 0.0, 65535.0, 1.0, 5.0, 0.0)
        ram7_addr_step_rate_adj = gtk.Adjustment(0.0, 0.0, 65535.0, 1.0, 5.0, 0.0)

        ram0_addr_step_rate_spin = gtk.SpinButton(ram0_addr_step_rate_adj, 0, 0)
        ram1_addr_step_rate_spin = gtk.SpinButton(ram1_addr_step_rate_adj, 0, 0)
        ram2_addr_step_rate_spin = gtk.SpinButton(ram2_addr_step_rate_adj, 0, 0)
        ram3_addr_step_rate_spin = gtk.SpinButton(ram3_addr_step_rate_adj, 0, 0)
        ram4_addr_step_rate_spin = gtk.SpinButton(ram4_addr_step_rate_adj, 0, 0)
        ram5_addr_step_rate_spin = gtk.SpinButton(ram5_addr_step_rate_adj, 0, 0)
        ram6_addr_step_rate_spin = gtk.SpinButton(ram6_addr_step_rate_adj, 0, 0)
        ram7_addr_step_rate_spin = gtk.SpinButton(ram7_addr_step_rate_adj, 0, 0)
        ram0_addr_step_rate_spin.show()
        ram1_addr_step_rate_spin.show()
        ram2_addr_step_rate_spin.show()
        ram3_addr_step_rate_spin.show()
        ram4_addr_step_rate_spin.show()
        ram5_addr_step_rate_spin.show()
        ram6_addr_step_rate_spin.show()
        ram7_addr_step_rate_spin.show()
        ram0_addr_step_rate_spin.set_wrap(True)
        ram1_addr_step_rate_spin.set_wrap(True)
        ram2_addr_step_rate_spin.set_wrap(True)
        ram3_addr_step_rate_spin.set_wrap(True)
        ram4_addr_step_rate_spin.set_wrap(True)
        ram5_addr_step_rate_spin.set_wrap(True)
        ram6_addr_step_rate_spin.set_wrap(True)
        ram7_addr_step_rate_spin.set_wrap(True)
        ram0_playback_rate_label = gtk.Label('Playback Rate (Hz): ')
        ram1_playback_rate_label = gtk.Label('Playback Rate (Hz): ')
        ram2_playback_rate_label = gtk.Label('Playback Rate (Hz): ')
        ram3_playback_rate_label = gtk.Label('Playback Rate (Hz): ')
        ram4_playback_rate_label = gtk.Label('Playback Rate (Hz): ')
        ram5_playback_rate_label = gtk.Label('Playback Rate (Hz): ')
        ram6_playback_rate_label = gtk.Label('Playback Rate (Hz): ')
        ram7_playback_rate_label = gtk.Label('Playback Rate (Hz): ')
        ram0_playback_rate_label.show()
        ram1_playback_rate_label.show()
        ram2_playback_rate_label.show()
        ram3_playback_rate_label.show()
        ram4_playback_rate_label.show()
        ram5_playback_rate_label.show()
        ram6_playback_rate_label.show()
        ram7_playback_rate_label.show()
        ram0_playback_rate_display = gtk.Entry()
        ram1_playback_rate_display = gtk.Entry()
        ram2_playback_rate_display = gtk.Entry()
        ram3_playback_rate_display = gtk.Entry()
        ram4_playback_rate_display = gtk.Entry()
        ram5_playback_rate_display = gtk.Entry()
        ram6_playback_rate_display = gtk.Entry()
        ram7_playback_rate_display = gtk.Entry()
        ram0_playback_rate_display.show()
        ram1_playback_rate_display.show()
        ram2_playback_rate_display.show()
        ram3_playback_rate_display.show()
        ram4_playback_rate_display.show()
        ram5_playback_rate_display.show()
        ram6_playback_rate_display.show()
        ram7_playback_rate_display.show()
        ram0_playback_rate_display.set_editable(False)
        ram1_playback_rate_display.set_editable(False)
        ram2_playback_rate_display.set_editable(False)
        ram3_playback_rate_display.set_editable(False)
        ram4_playback_rate_display.set_editable(False)
        ram5_playback_rate_display.set_editable(False)
        ram6_playback_rate_display.set_editable(False)
        ram7_playback_rate_display.set_editable(False)
        ram0_mode_control_label = gtk.Label('Mode Control: ')
        ram1_mode_control_label = gtk.Label('Mode Control: ')
        ram2_mode_control_label = gtk.Label('Mode Control: ')
        ram3_mode_control_label = gtk.Label('Mode Control: ')
        ram4_mode_control_label = gtk.Label('Mode Control: ')
        ram5_mode_control_label = gtk.Label('Mode Control: ')
        ram6_mode_control_label = gtk.Label('Mode Control: ')
        ram7_mode_control_label = gtk.Label('Mode Control: ')
        ram0_mode_control_label.show()
        ram1_mode_control_label.show()
        ram2_mode_control_label.show()
        ram3_mode_control_label.show()
        ram4_mode_control_label.show()
        ram5_mode_control_label.show()
        ram6_mode_control_label.show()
        ram7_mode_control_label.show()
        ram0_mode_combo = gtk.combo_box_new_text()
        ram1_mode_combo = gtk.combo_box_new_text()
        ram2_mode_combo = gtk.combo_box_new_text()
        ram3_mode_combo = gtk.combo_box_new_text()
        ram4_mode_combo = gtk.combo_box_new_text()
        ram5_mode_combo = gtk.combo_box_new_text()
        ram6_mode_combo = gtk.combo_box_new_text()
        ram7_mode_combo = gtk.combo_box_new_text()
        ram0_mode_combo.show()
        ram1_mode_combo.show()
        ram2_mode_combo.show()
        ram3_mode_combo.show()
        ram4_mode_combo.show()
        ram5_mode_combo.show()
        ram6_mode_combo.show()
        ram7_mode_combo.show()
        ram0_mode_combo.append_text('Direct Switch')
        ram1_mode_combo.append_text('Direct Switch')
        ram2_mode_combo.append_text('Direct Switch')
        ram3_mode_combo.append_text('Direct Switch')
        ram4_mode_combo.append_text('Direct Switch')
        ram5_mode_combo.append_text('Direct Switch')
        ram6_mode_combo.append_text('Direct Switch')
        ram7_mode_combo.append_text('Direct Switch')
        ram0_mode_combo.append_text('Ramp-up')
        ram1_mode_combo.append_text('Ramp-up')
        ram2_mode_combo.append_text('Ramp-up')
        ram3_mode_combo.append_text('Ramp-up')
        ram4_mode_combo.append_text('Ramp-up')
        ram5_mode_combo.append_text('Ramp-up')
        ram6_mode_combo.append_text('Ramp-up')
        ram7_mode_combo.append_text('Ramp-up')
        ram0_mode_combo.append_text('Bidirectional Ramp')
        ram1_mode_combo.append_text('Bidirectional Ramp')
        ram2_mode_combo.append_text('Bidirectional Ramp')
        ram3_mode_combo.append_text('Bidirectional Ramp')
        ram4_mode_combo.append_text('Bidirectional Ramp')
        ram5_mode_combo.append_text('Bidirectional Ramp')
        ram6_mode_combo.append_text('Bidirectional Ramp')
        ram7_mode_combo.append_text('Bidirectional Ramp')
        ram0_mode_combo.append_text('Continuous Bidirectional Ramp')
        ram1_mode_combo.append_text('Continuous Bidirectional Ramp')
        ram2_mode_combo.append_text('Continuous Bidirectional Ramp')
        ram3_mode_combo.append_text('Continuous Bidirectional Ramp')
        ram4_mode_combo.append_text('Continuous Bidirectional Ramp')
        ram5_mode_combo.append_text('Continuous Bidirectional Ramp')
        ram6_mode_combo.append_text('Continuous Bidirectional Ramp')
        ram7_mode_combo.append_text('Continuous Bidirectional Ramp')
        ram0_mode_combo.append_text('Continuous Recirculate')
        ram1_mode_combo.append_text('Continuous Recirculate')
        ram2_mode_combo.append_text('Continuous Recirculate')
        ram3_mode_combo.append_text('Continuous Recirculate')
        ram4_mode_combo.append_text('Continuous Recirculate')
        ram5_mode_combo.append_text('Continuous Recirculate')
        ram6_mode_combo.append_text('Continuous Recirculate')
        ram7_mode_combo.append_text('Continuous Recirculate')
        ram0_mode_combo.set_active(0)
        ram1_mode_combo.set_active(0)
        ram2_mode_combo.set_active(0)
        ram3_mode_combo.set_active(0)
        ram4_mode_combo.set_active(0)
        ram5_mode_combo.set_active(0)
        ram6_mode_combo.set_active(0)
        ram7_mode_combo.set_active(0)
        ram0_zero_crossing_button = gtk.CheckButton('Zero Crossing')
        ram1_zero_crossing_button = gtk.CheckButton('Zero Crossing')
        ram2_zero_crossing_button = gtk.CheckButton('Zero Crossing')
        ram3_zero_crossing_button = gtk.CheckButton('Zero Crossing')
        ram4_zero_crossing_button = gtk.CheckButton('Zero Crossing')
        ram5_zero_crossing_button = gtk.CheckButton('Zero Crossing')
        ram6_zero_crossing_button = gtk.CheckButton('Zero Crossing')
        ram7_zero_crossing_button = gtk.CheckButton('Zero Crossing')
        ram0_zero_crossing_button.show()
        ram1_zero_crossing_button.show()
        ram2_zero_crossing_button.show()
        ram3_zero_crossing_button.show()
        ram4_zero_crossing_button.show()
        ram5_zero_crossing_button.show()
        ram6_zero_crossing_button.show()
        ram7_zero_crossing_button.show()
        ram0_no_dwell_button = gtk.CheckButton('No Dwell')
        ram1_no_dwell_button = gtk.CheckButton('No Dwell')
        ram2_no_dwell_button = gtk.CheckButton('No Dwell')
        ram3_no_dwell_button = gtk.CheckButton('No Dwell')
        ram4_no_dwell_button = gtk.CheckButton('No Dwell')
        ram5_no_dwell_button = gtk.CheckButton('No Dwell')
        ram6_no_dwell_button = gtk.CheckButton('No Dwell')
        ram7_no_dwell_button = gtk.CheckButton('No Dwell')
        ram0_no_dwell_button.show()
        ram1_no_dwell_button.show()
        ram2_no_dwell_button.show()
        ram3_no_dwell_button.show()
        ram4_no_dwell_button.show()
        ram5_no_dwell_button.show()
        ram6_no_dwell_button.show()
        ram7_no_dwell_button.show()
        
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram0_begin_addr_label, False, False, 5)
        hbox.pack_start(ram0_begin_addr_display, False, False, 5)
        hbox.pack_start(ram0_final_addr_label, False, False, 5)
        hbox.pack_start(ram0_final_addr_display, False, False, 5)
        hbox.pack_start(ram0_addr_step_rate_label, False, False, 5)
        hbox.pack_start(ram0_addr_step_rate_spin, False, False, 5)
        ram0_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram0_mode_control_label, False, False, 5)
        hbox.pack_start(ram0_mode_combo, False, False, 5)
        hbox.pack_start(ram0_zero_crossing_button, False, False, 5)
        hbox.pack_start(ram0_no_dwell_button, False, False, 5)
        ram0_vbox.pack_start(hbox, False, False, 10)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram0_playback_rate_label, False, False, 5)
        hbox.pack_start(ram0_playback_rate_display, False, False, 5)
        ram0_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram1_begin_addr_label, False, False, 5)
        hbox.pack_start(ram1_begin_addr_display, False, False, 5)
        hbox.pack_start(ram1_final_addr_label, False, False, 5)
        hbox.pack_start(ram1_final_addr_display, False, False, 5)
        hbox.pack_start(ram1_addr_step_rate_label, False, False, 5)
        hbox.pack_start(ram1_addr_step_rate_spin, False, False, 5)
        ram1_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram1_mode_control_label, False, False, 5)
        hbox.pack_start(ram1_mode_combo, False, False, 5)
        hbox.pack_start(ram1_zero_crossing_button, False, False, 5)
        hbox.pack_start(ram1_no_dwell_button, False, False, 5)
        ram1_vbox.pack_start(hbox, False, False, 10)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram1_playback_rate_label, False, False, 5)
        hbox.pack_start(ram1_playback_rate_display, False, False, 5)
        ram1_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram2_begin_addr_label, False, False, 5)
        hbox.pack_start(ram2_begin_addr_display, False, False, 5)
        hbox.pack_start(ram2_final_addr_label, False, False, 5)
        hbox.pack_start(ram2_final_addr_display, False, False, 5)
        hbox.pack_start(ram2_addr_step_rate_label, False, False, 5)
        hbox.pack_start(ram2_addr_step_rate_spin, False, False, 5)
        ram2_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram2_mode_control_label, False, False, 5)
        hbox.pack_start(ram2_mode_combo, False, False, 5)
        hbox.pack_start(ram2_zero_crossing_button, False, False, 5)
        hbox.pack_start(ram2_no_dwell_button, False, False, 5)
        ram2_vbox.pack_start(hbox, False, False, 10)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram2_playback_rate_label, False, False, 5)
        hbox.pack_start(ram2_playback_rate_display, False, False, 5)
        ram2_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram3_begin_addr_label, False, False, 5)
        hbox.pack_start(ram3_begin_addr_display, False, False, 5)
        hbox.pack_start(ram3_final_addr_label, False, False, 5)
        hbox.pack_start(ram3_final_addr_display, False, False, 5)
        hbox.pack_start(ram3_addr_step_rate_label, False, False, 5)
        hbox.pack_start(ram3_addr_step_rate_spin, False, False, 5)
        ram3_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram3_mode_control_label, False, False, 5)
        hbox.pack_start(ram3_mode_combo, False, False, 5)
        hbox.pack_start(ram3_zero_crossing_button, False, False, 5)
        hbox.pack_start(ram3_no_dwell_button, False, False, 5)
        ram3_vbox.pack_start(hbox, False, False, 10)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram3_playback_rate_label, False, False, 5)
        hbox.pack_start(ram3_playback_rate_display, False, False, 5)
        ram3_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram4_begin_addr_label, False, False, 5)
        hbox.pack_start(ram4_begin_addr_display, False, False, 5)
        hbox.pack_start(ram4_final_addr_label, False, False, 5)
        hbox.pack_start(ram4_final_addr_display, False, False, 5)
        hbox.pack_start(ram4_addr_step_rate_label, False, False, 5)
        hbox.pack_start(ram4_addr_step_rate_spin, False, False, 5)
        ram4_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram4_mode_control_label, False, False, 5)
        hbox.pack_start(ram4_mode_combo, False, False, 5)
        hbox.pack_start(ram4_zero_crossing_button, False, False, 5)
        hbox.pack_start(ram4_no_dwell_button, False, False, 5)
        ram4_vbox.pack_start(hbox, False, False, 10)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram4_playback_rate_label, False, False, 5)
        hbox.pack_start(ram4_playback_rate_display, False, False, 5)
        ram4_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram5_begin_addr_label, False, False, 5)
        hbox.pack_start(ram5_begin_addr_display, False, False, 5)
        hbox.pack_start(ram5_final_addr_label, False, False, 5)
        hbox.pack_start(ram5_final_addr_display, False, False, 5)
        hbox.pack_start(ram5_addr_step_rate_label, False, False, 5)
        hbox.pack_start(ram5_addr_step_rate_spin, False, False, 5)
        ram5_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram5_mode_control_label, False, False, 5)
        hbox.pack_start(ram5_mode_combo, False, False, 5)
        hbox.pack_start(ram5_zero_crossing_button, False, False, 5)
        hbox.pack_start(ram5_no_dwell_button, False, False, 5)
        ram5_vbox.pack_start(hbox, False, False, 10)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram5_playback_rate_label, False, False, 5)
        hbox.pack_start(ram5_playback_rate_display, False, False, 5)
        ram5_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram6_begin_addr_label, False, False, 5)
        hbox.pack_start(ram6_begin_addr_display, False, False, 5)
        hbox.pack_start(ram6_final_addr_label, False, False, 5)
        hbox.pack_start(ram6_final_addr_display, False, False, 5)
        hbox.pack_start(ram6_addr_step_rate_label, False, False, 5)
        hbox.pack_start(ram6_addr_step_rate_spin, False, False, 5)
        ram6_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram6_mode_control_label, False, False, 5)
        hbox.pack_start(ram6_mode_combo, False, False, 5)
        hbox.pack_start(ram6_zero_crossing_button, False, False, 5)
        hbox.pack_start(ram6_no_dwell_button, False, False, 5)
        ram6_vbox.pack_start(hbox, False, False, 10)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram6_playback_rate_label, False, False, 5)
        hbox.pack_start(ram6_playback_rate_display, False, False, 5)
        ram6_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram7_begin_addr_label, False, False, 5)
        hbox.pack_start(ram7_begin_addr_display, False, False, 5)
        hbox.pack_start(ram7_final_addr_label, False, False, 5)
        hbox.pack_start(ram7_final_addr_display, False, False, 5)
        hbox.pack_start(ram7_addr_step_rate_label, False, False, 5)
        hbox.pack_start(ram7_addr_step_rate_spin, False, False, 5)
        ram7_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram7_mode_control_label, False, False, 5)
        hbox.pack_start(ram7_mode_combo, False, False, 5)
        hbox.pack_start(ram7_zero_crossing_button, False, False, 5)
        hbox.pack_start(ram7_no_dwell_button, False, False, 5)
        ram7_vbox.pack_start(hbox, False, False, 10)
        hbox = gtk.HBox()
        hbox.show()
        hbox.pack_start(ram7_playback_rate_label, False, False, 5)
        hbox.pack_start(ram7_playback_rate_display, False, False, 5)
        ram7_vbox.pack_start(hbox)
        
        ## QSK Window
        qsk_enable_digital_ramp_button = gtk.CheckButton('Enable Digital Ramp Generator')
        qsk_enable_digital_ramp_frame = gtk.Frame()
        qsk_mode_frame = gtk.Frame('Mode')
        mode_freq = gtk.RadioButton(None, 'Frequency')
        mode_phase = gtk.RadioButton(mode_freq, 'Phase')
        mode_amplitude = gtk.RadioButton(mode_phase, 'Amplitude')
        qsk_auto_clr_button = gtk.CheckButton('Auto Clear Digital Ramp Accum.')
        qsk_clr_ramp_button = gtk.CheckButton('Clear Digital Ramp Accumulator')
        qsk_load_drr_button = gtk.CheckButton('Load DRR @ I/O Update')
        qsk_sweep_freq0_label = gtk.Label('Sweep Frequency 0: ')
        qsk_sweep_freq0_display = gtk.Entry()
        qsk_sweep_freq0_MHz = gtk.Label('MHz')
        qsk_rising_step_label = gtk.Label('Rising Step Size: ')
        qsk_rising_step_display = gtk.Entry()
        qsk_rising_step_MHz = gtk.Label('MHz')
        qsk_rising_interval_label = gtk.Label('Rising Step Interval: ')
        qsk_rising_interval_display = gtk.Entry()
        qsk_rising_interval_MHz = gtk.Label('(us)')
        qsk_separator = gtk.HSeparator()
        qsk_sweep_freq1_label = gtk.Label('Sweep Frequency 1: ')
        qsk_sweep_freq1_display = gtk.Entry()
        qsk_sweep_freq1_MHz = gtk.Label('MHz')
        qsk_falling_step_label = gtk.Label('Falling Step Size: ')
        qsk_falling_step_display = gtk.Entry()
        qsk_falling_step_MHz = gtk.Label('MHz')
        qsk_falling_interval_label = gtk.Label('Falling Step Interval: ')
        qsk_falling_interval_display = gtk.Entry()
        qsk_falling_interval_MHz = gtk.Label('(us)')
        qsk_no_dwell_high_button = gtk.CheckButton('No Dwell High')
        qsk_no_dwell_low_button = gtk.CheckButton('No Dwell Low')
        qsk_up_button = gtk.Button()
        image = gtk.image_new_from_stock(gtk.STOCK_GO_UP, gtk.ICON_SIZE_BUTTON)
        qsk_up_button.set_image(image)
        qsk_down_button = gtk.Button()
        image = gtk.image_new_from_stock(gtk.STOCK_GO_DOWN, gtk.ICON_SIZE_BUTTON)
        qsk_down_button.set_image(image)
        qsk_pause_button = gtk.Button()
        image = gtk.image_new_from_stock(gtk.STOCK_MEDIA_PAUSE, gtk.ICON_SIZE_BUTTON)
        qsk_pause_button.set_image(image)
        qsk_ramp_finished_label = gtk.Label('Ramp Finished: ')
        qsk_ramp_finished_image = gtk.image_new_from_stock(gtk.STOCK_NO, gtk.ICON_SIZE_BUTTON)
        #--
        qsk_enable_output_shift_keying_button = gtk.CheckButton('Enable Output Shift Keying')
        qsk_enable_osk_frame = gtk.Frame()
        qsk_sf_label = gtk.Label('Amplitude Scale Factor: ')
        qsk_sf_adj = gtk.Adjustment(0.00000, 0.00000, 1.00000, 0.00001, 0.00005, 0.0)
        qsk_sf_spin = gtk.SpinButton(qsk_sf_adj, 0, 0)
        qsk_external_osk_pin_checkbutton = gtk.CheckButton('Use External OSK Pin')
        qsk_external_osk_pin_button = gtk.Button('OSK Pin')
        qsk_enable_auto_osk_button = gtk.CheckButton('Enable Auto OSK')
        qsk_enable_auto_osk_frame = gtk.Frame()
        qsk_amplitude_ramp_rate_label = gtk.Label('Amplitude Ramp Rate: ')
        qsk_amplitude_ramp_rate_display = gtk.Entry()
        qsk_amplitude_ramp_rate_us = gtk.Label('(us)')
        qsk_amplitude_step_adjust_label = gtk.Label('Amplitude Step Adjust: ')
        qsk_amplitude_step_adjust_combo = gtk.combo_box_new_text()
        qsk_amplitude_step_adjust_combo.append_text('1')
        qsk_amplitude_step_adjust_combo.append_text('2')
        qsk_amplitude_step_adjust_combo.append_text('4')
        qsk_amplitude_step_adjust_combo.append_text('8')
        qsk_amplitude_step_adjust_combo.set_active(0)
        qsk_load_arr_button = gtk.CheckButton('Load ARR @ I/O Update')
        qsk_auxiliary_sources_frame = gtk.Frame('Auxiliary Sources')
        qsk_output_freq_label = gtk.Label('Output Frequency: ')
        qsk_output_freq_display = gtk.Entry()
        qsk_output_freq_MHz = gtk.Label('MHz')
        qsk_phase_offset_label = gtk.Label('Phase Offset: ')
        qsk_phase_offset_adj = gtk.Adjustment(0.0, 0.0, 360.0, 0.001, 0.005, 0.0)
        qsk_phase_offset_spin = gtk.SpinButton(qsk_phase_offset_adj, 0, 0)
        qsk_phase_offset_deg = gtk.Label('Deg')
        
        # Load the widgets
        qsk_vbox0 = gtk.VBox()
        qsk_box.pack_start(qsk_vbox0)
        qsk_vbox1 = gtk.VBox()
        qsk_box.pack_start(qsk_vbox1)
        qsk_vbox0.pack_start(qsk_enable_digital_ramp_button)
        qsk_vbox0.pack_start(qsk_enable_digital_ramp_frame)
        qsk_enable_digital_ramp_vbox = gtk.VBox()
        qsk_enable_digital_ramp_frame.add(qsk_enable_digital_ramp_vbox)
        hbox = gtk.HBox()        
        vbox = gtk.VBox()
        qsk_mode_frame.add(vbox)
        vbox.pack_start(mode_freq)
        vbox.pack_start(mode_phase)
        vbox.pack_start(mode_amplitude)
        hbox.pack_start(qsk_mode_frame)
        qsk_mode_frame_other = gtk.Frame()
        vbox = gtk.VBox()
        qsk_mode_frame_other.add(vbox)
        vbox.pack_start(qsk_auto_clr_button)
        vbox.pack_start(qsk_clr_ramp_button)
        vbox.pack_start(qsk_load_drr_button)
        hbox.pack_start(qsk_mode_frame_other)
        qsk_enable_digital_ramp_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.pack_start(qsk_sweep_freq0_label, False, False, 5)
        hbox.pack_start(qsk_sweep_freq0_display, False, False, 5)
        hbox.pack_start(qsk_sweep_freq0_MHz, False, False, 5)
        qsk_enable_digital_ramp_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.pack_start(qsk_rising_step_label, False, False, 5)
        hbox.pack_start(qsk_rising_step_display, False, False, 5)
        hbox.pack_start(qsk_rising_step_MHz, False, False, 5)
        qsk_enable_digital_ramp_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.pack_start(qsk_rising_interval_label, False, False, 5)
        hbox.pack_start(qsk_rising_interval_display, False, False, 5)
        hbox.pack_start(qsk_rising_interval_MHz, False, False, 5)
        qsk_enable_digital_ramp_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.pack_start(qsk_sweep_freq1_label, False, False, 5)
        hbox.pack_start(qsk_sweep_freq1_display, False, False, 5)
        hbox.pack_start(qsk_sweep_freq1_MHz, False, False, 5)
        qsk_enable_digital_ramp_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.pack_start(qsk_falling_step_label, False, False, 5)
        hbox.pack_start(qsk_falling_step_display, False, False, 5)
        hbox.pack_start(qsk_falling_step_MHz, False, False, 5)
        qsk_enable_digital_ramp_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.pack_start(qsk_falling_interval_label, False, False, 5)
        hbox.pack_start(qsk_falling_interval_display, False, False, 5)
        hbox.pack_start(qsk_falling_interval_MHz, False, False, 5)
        qsk_enable_digital_ramp_vbox.pack_start(hbox)
        qsk_enable_digital_ramp_vbox.pack_start(qsk_no_dwell_high_button, False, False, 5)
        qsk_enable_digital_ramp_vbox.pack_start(qsk_no_dwell_low_button, False, False, 5)
        hbox = gtk.HBox()
        hbox.pack_start(qsk_up_button, False, False, 5)
        hbox.pack_start(qsk_down_button, False, False, 5)
        hbox.pack_start(qsk_pause_button, False, False, 5)
        hbox.pack_start(qsk_ramp_finished_label, False, False, 5)
        hbox.pack_start(qsk_ramp_finished_image, False, False, 5)
        qsk_enable_digital_ramp_vbox.pack_start(hbox)
        
        qsk_vbox1.pack_start(qsk_enable_output_shift_keying_button, False, False, 5)
        qsk_vbox1.pack_start(qsk_enable_osk_frame)
        qsk_enable_osk_vbox = gtk.VBox()
        qsk_enable_osk_frame.add(qsk_enable_osk_vbox)
        qsk_enable_auto_vbox = gtk.VBox()
        qsk_enable_auto_osk_frame.add(qsk_enable_auto_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(qsk_sf_label, False, False, 5)
        hbox.pack_start(qsk_sf_spin, False, False, 5)
        qsk_enable_osk_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.pack_start(qsk_external_osk_pin_checkbutton, False, False, 5)
        hbox.pack_start(qsk_external_osk_pin_button, False, False, 5)
        qsk_enable_osk_vbox.pack_start(hbox)
        qsk_enable_osk_vbox.pack_start(qsk_enable_auto_osk_button, False, False, 5)
        qsk_enable_osk_vbox.pack_start(qsk_enable_auto_osk_frame)
        hbox = gtk.HBox()
        hbox.pack_start(qsk_amplitude_ramp_rate_label, False, False, 5)
        hbox.pack_start(qsk_amplitude_ramp_rate_display, False, False, 5)
        hbox.pack_start(qsk_amplitude_ramp_rate_us, False, False, 5)
        qsk_enable_auto_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.pack_start(qsk_amplitude_step_adjust_label, False, False, 5)
        hbox.pack_start(qsk_amplitude_step_adjust_combo, False, False, 5)
        qsk_enable_auto_vbox.pack_start(hbox)
        qsk_enable_auto_vbox.pack_start(qsk_load_arr_button, False, False, 5)
        qsk_vbox1.pack_start(qsk_auxiliary_sources_frame)
        qsk_auxiliary_sources_vbox = gtk.VBox()
        qsk_auxiliary_sources_frame.add(qsk_auxiliary_sources_vbox)
        hbox = gtk.HBox()
        hbox.pack_start(qsk_output_freq_label, False, False, 5)
        hbox.pack_start(qsk_output_freq_display, False, False, 5)
        hbox.pack_start(qsk_output_freq_MHz, False, False, 5)
        qsk_auxiliary_sources_vbox.pack_start(hbox)
        hbox = gtk.HBox()
        hbox.pack_start(qsk_phase_offset_label, False, False, 5)
        hbox.pack_start(qsk_phase_offset_spin, False, False, 5)
        hbox.pack_start(qsk_phase_offset_deg, False, False, 5)
        qsk_auxiliary_sources_vbox.pack_start(hbox)

        ## Register Values Window

        ## Initialize
        enable_multi_frame.set_sensitive(False)
        internal_io_frame.set_sensitive(False)


        ## Callbacks
        enable_multiplier_button.connect('clicked', cb_enable_multiplier, (self.sysclk, sysclk_display, multiplier_spin, enable_multi_frame))
        multiplier_spin.connect('value-changed', cb_multiplier_changed, (self.sysclk, sysclk_display))
        io_button.connect('clicked', cb_enable_internal_io_update, internal_io_frame)
        io_combo.connect('changed', cb_internal_io_update_changed, (self.sysclk, io_display))
        

        enable_RAM_button.connect('clicked', cb_profile_window_notebook, ram_notebook, profile_notebook, profile_vbox)
        ## load_RAM_button.connect('clicked', cb_load_RAM, self)        
        ## load_RAM_FILE_button.connect('clicked', cb_load_RAM_file, self)














    def __init_about_dialog__(self):
        """ Method to create the about dialog. """

        def about_url_cb(dialog, link, user_data):
            """!
            Call back function to test url for the about dialog
            @param dialog about dialog object
            @param link url link that was clicked
            @param user_data user data that was passed in
            """
            gnomevfs.url_show(link)

        self.aboutdialog = gtk.AboutDialog()
        self.aboutdialog.set_name("DDS AD9910")
        self.aboutdialog.set_license(__doc__)
        self.aboutdialog.set_version('0.1')
        self.aboutdialog.set_copyright("2010")
        self.aboutdialog.set_authors(['Newell Jensen'])
        gtk.about_dialog_set_url_hook(about_url_cb, None)
        self.aboutdialog.set_website('http://www.gempillar.com')
        self.aboutdialog.set_translator_credits('translator-credits')
        self.aboutdialog.set_transient_for(self)



        


